repositories:
- name: "mocaccino-desktop-dev"
  url: "quay.io/mocaccino/desktop"
  type: "docker"
  github: "https://github.com/mocaccinoOS/desktop"
- name: "mocaccino-community"
  url: "quay.io/mocaccino/mocaccino-community"
  type: "docker"
  github: "https://github.com/mocaccinoOS/community-repository"
- name: "mocaccino-micro"
  type: "docker"
  url: "quay.io/mocaccino/micro"
  github: "https://github.com/mocaccinoOS/mocaccino-micro"
- name: "mocaccino-musl-universe"
  type: "docker"
  url: "quay.io/mocaccino/musl-universe"
  github: "https://github.com/mocaccinoOS/mocaccino-musl-universe"
- name: "kernel-dev"
  url: "quay.io/mocaccino/kernel"
  github: "https://github.com/mocaccinoOS/kernel-repo"


BaseUrl: "https://labs.mocaccino.org"
