repositories:
- name: "mocaccino-desktop-dev"
  url: "https://get.mocaccino.org/mocaccino-desktop"
  github: "https://github.com/mocaccinoOS/desktop"
- name: "mocaccino-community"
  url: "quay.io/mocaccino/mocaccino-community"
  type: "docker"
  github: "https://github.com/mocaccinoOS/community-repository"
- name: "mocaccino-portage-tree"
  url: "https://get.mocaccino.org/mocaccino-portage-tree"
  github: "https://github.com/mocaccinoOS/portage-tree"
- name: "mocaccino-portage-tree-stable"
  url: "https://get.mocaccino.org/mocaccino-portage-tree-stable"
  github: "https://github.com/mocaccinoOS/portage-tree"
- name: "mocaccino-micro"
  url: "https://get.mocaccino.org/mocaccino-micro"
  github: "https://github.com/mocaccinoOS/mocaccino-micro"
- name: "mocaccino-micro-stable"
  url: "https://get.mocaccino.org/mocaccino-micro-stable"
  github: "https://github.com/mocaccinoOS/mocaccino-micro"
- name: "mocaccino-musl-universe"
  url: "https://get.mocaccino.org/mocaccino-musl-universe"
  github: "https://github.com/mocaccinoOS/mocaccino-musl-universe"
- name: "mocaccino-musl-universe-stable"
  url: "https://get.mocaccino.org/mocaccino-musl-universe-stable"
  github: "https://github.com/mocaccinoOS/mocaccino-musl-universe"
- name: "kernel-dev"
  url: "https://get.mocaccino.org/mocaccino-kernel"
  github: "https://github.com/mocaccinoOS/kernel-repo"


BaseUrl: "https://labs.mocaccino.org"
